---
# This role will install cloudera agent package

- name: Install cloiudera manager package
  yum: name={{ item }} state=latest
  with_items:
    - java-1.8.0-openjdk
    - cloudera-manager-agent
    - mysql-connector-java
  async: 7200
  poll: 10

- name: Make sure no other jdk package
  yum: name={{ item }} state=absent
  with_items:
   - jdk

- name: Create /etc/cloudera-scm-agent/config.ini
  template: src=etc/cloudera-scm-agent/config_client.ini.j2 dest=/etc/cloudera-scm-agent/config.ini owner=cloudera-scm group=cloudera-scm mode=0644

- name: Start Cloudera Manager agent on clients
  service: name=cloudera-scm-agent state=started enabled=true
